# Generated by Django 5.1.2 on 2024-10-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desig', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=15)),
                ('bcs_batch', models.CharField(max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('last_blood_donation', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
