# Generated by Django 5.1.2 on 2024-10-28 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
