# Generated by Django 5.1.2 on 2024-10-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0002_donor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
